name: pro_stress_app
description: "Ultimate Stress Test V18"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  battery_plus: ^6.1.0
  wakelock_plus: ^1.2.8
  path_provider: ^2.1.2
  screen_brightness: ^1.0.1

flutter:
  uses-material-design: true
